import { AspectType } from '@/lib/types';

export const QUESTIONS: Record<AspectType, string[]> = {
  skill: [
    "What software, tools, technologies or technical methodologies are you proficient in?",
    "What skills do you have that set you apart from others?",
    "What social skills or soft skills do you consider your strongest?",
    "What leadership or management skills do you bring to a project or team?",
    "Which communication skills do you consider your strongest: public speaking, writing, or another?"
  ],
  knowledge: [
    "What unique insights have you gained from your current or past job roles?",
    "Are there any niche or unconventional tools that you have expertise in using?",
    "What languages do you know?",
    "Do you any mental models or frameworks that you find particularly useful?",
    "From software applications to hardware gadgets, what are your must-have tools for enhancing productivity, creativity, and well-being?",
    "What specialized knowledge do you have that you believe is rare in your industry or area of study?",
    "What's a concept or idea you've come to understand that you wish more people knew about?",
    "What's an unconventional source of wisdom or knowledge in your life?",
    "What's a lesson you've learned from a failure or mistake that you feel is beneficial?",
    "Can you name the tools that significantly enhance your creative projects?",
    "What's an underappreciated asset in your toolbox that you believe more people should know about?",
  ],
  accomplishment: [
    "What professional achievements are you most proud of?",
    "What would you say are your most significant accomplishments?",
    "What did you learn from your successes and failures?",   
  ],
  strength: [
    "What is something you find easy to do that others might struggle with?",
    "What unique personal quality do you believe has contributed most to your successes?",
    "How do others benefit from your strengths?",
    "What strength do you wish to cultivate or enhance?",
    "What innate talent do you have that you're most proud of?",
    "What strength do you possess that people often commend you for?",
    "What aspect of your personality sets you apart in team environments or collaborative projects?",
  ],
  interest: [
    "Are there any ideas you like to think about?",
    "What topics or subjects are you curious about?",
    "What subject could you read about or study for hours on end?",
    "How do you like to express yourself creatively or artistically?",
    "What do you like to talk about?",
    "What captures your attention and sparks your imagination?",
    "What are some things that you find yourself researching or learning about?",
    "What are your favorite activities, hobbies?",
  ],
  value: [
    "What principles guide your decision-making process?",
    "Which values do you consider non-negotiable in your life?",
    "Can you describe a belief that has shaped the way you view the world?",
    "What cultural or spiritual beliefs deeply impact your daily life?",
    "How do your values influence your relationships with others?",
    "What ethical standards do you hold yourself to in professional settings?",
    "Is there a philosophy that you live by? If so, how does it influence your actions?",
  ],
  dream: [
    "What dreams do you have for your future?",
    "In a decade, what would you like to have accomplished?",
    "Describe your dream project. What would it look like? What would it achieve? Why is this important to you?",
    "At the end of your life, what would you like to be remembered for?",
    "What innovation or invention do you dream of creating?",
    "If you could instantly transform one aspect of the world, what would it be?",
  ],
  inspiration: [
    "Who do you consider your biggest role model?",
    "What ideas or philosophies that have influenced you?",
    "Name a book or movie that changed or formed your perspective.",
    "Who inspires you the most?",
    "What's a piece of advice that has stayed with you?",
    "Who in your life has had the biggest impact on your way of thinking?",
    "What have documentaries or books introduced to you that has changed the way you think?",
    "Are there any experiences that have shaped how you view the world, or the way you think?",
    "What personal challenge has shaped you significantly?",
    "What personal success are you hoping to achieve that might inspire others?",
  ],
  innovation: [
    "Technology is advancing rapidly, but it's still not adopted in so many areas of life. Where do you think it's most needed?",
    "What's the most critical problem nobody is working on?",
    "AI is here, in which unconvential way do you think it can be used?",
    "In what area do you think more innovation is needed?",
    "What really annoys you about the place you live in, that you think could be improved with a bit of innovation?",
    "How do you think technology could be leveraged to improve education or healthcare in your community?",

  ],
  impact: [
    "What's a global issue you believe is critical for the future?",
    "What's an issue you feel is not getting enough attention?",
    "If you could advocate for one global cause, what would it be?",
    "What's an initiative or project do you admire for its impact?",
    "What do you perceive as the most pressing social or cultural problems in your society today?",
    "What do we need more of to combat social challenges?",
    "In what ways can people make a positive impact on societal issues?",
    "What societal change would you like to see in your lifetime?",
  ],
  community: [
    "What type of community do you want to build or be a part of?",
    "What's one local issue you're actively involved in or care about?",
    "What communities are you a part of that bring meaning to your life?",
    "Are there any initiatives or movements you know of that are addressing important problems?",
    "What's an area in your community where you see an opportunity for positive change?",
    "What communities or groups do you feel most connected to?",
    "What's a community project you'd like to be a part of?",
    "What do you look for in an online community when joining?"
  ],
  progress: [
    "In what areas do you want to see progress in your country in the next 10 years?",
    "In what areas do you want to see progress in the world in the next 10 years?",
    "Which ideas are not being taken too seriously as a way to improve the conditions of people, and yet maybe they should?",
    "What practical steps can be taken to promote environmental sustainability?",
    "What are the main challenges standing in the way of progress you want to see in the world?",
    "Thinking about your city, what initiative or development do you think could significantly enhance the quality of life for its residents?",
    "On a national level, what progress do you think is essential for your country to address current challenges and improve the well-being of its citizens?",
    "What are the key areas where you believe progress is needed to create a better future for all?",
  ],
  "business-idea": [
    "What's a business idea you've had that you believe could be successful?",
    "If you could become a solo entrepreneur, what would you do?",
    "What business ideas do you constantly think about?",
    "What are some problems you've noticed around you that might turn into business opportunities?",
    "What's a business idea you've had that you believe could be successful?",
    "What's one type of business everyone seems to be doing, but you think you could do better?",
    "Do you have a startup idea you like to think about? What is it?",
  ],
  career: [
    "What is your current role at work?",
    "What are your favorite aspects of your current or previous job?",
    "What do you dislike and even hate about your work?",
    "What have you learned about the type of job you enjoy doing?",
    "What tasks or projects do you find most rewarding in your current job?",
    "If you were to start a new career tomorrow, what field would you choose?",
    "What are the most important things you're looking for in a job?",
    "If you had to do a PHD starting tomorrow based entirely on what you find intellectually interesting what would you do it on?",
  ],
  "financial-freedom": [
    "Who are your ideal clients? Startups, SMEs, corporations, ...?",
    "Are you open to ",
    "What's a freelance project you'd like to work on in the future?",
    "What's a one day business you can spin up today?",
  ],
  growth: [
    "What area of your professional expertise are you looking to deepen?",
    "Are there any new technologies or tools you want to learn?",
    "Is there a particular language, either programming or spoken, you aim to learn?",
    "What soft skill (e.g., communication, leadership, time management) do you believe will make the biggest impact on your growth?",
    "What health or wellness practice do you want to adopt to improve your well-being?",
    "Is there a specific industry knowledge or insight you aim to gain to better understand your field?",
    "What personal project are you planning that you believe will contribute to your growth?",
    "Do you have plans to attend any workshops, seminars, or conferences that focus on areas you wish to grow in?",
    "What new book, podcast, or other resource are you looking to explore to gain knowledge or inspiration?"
  ],
};
